/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Ad } from './models/Ad';
export type { AdCreate } from './models/AdCreate';
export type { AdList } from './models/AdList';
export type { AdPatch } from './models/AdPatch';
export { AdPositionEnum } from './models/AdPositionEnum';
export type { AreaOfInterest } from './models/AreaOfInterest';
export type { AreaOfInterestList } from './models/AreaOfInterestList';
export type { AuthResponse } from './models/AuthResponse';
export type { Badge } from './models/Badge';
export type { BadgeCreate } from './models/BadgeCreate';
export type { BadgeList } from './models/BadgeList';
export type { BadgePatch } from './models/BadgePatch';
export { BadgeTypeEnum } from './models/BadgeTypeEnum';
export type { BaseBulkSearchResult } from './models/BaseBulkSearchResult';
export type { Blog } from './models/Blog';
export type { BlogCreate } from './models/BlogCreate';
export type { BlogList } from './models/BlogList';
export type { Body_change_team_icon_admin_change_team_icon__team_id__post } from './models/Body_change_team_icon_admin_change_team_icon__team_id__post';
export type { Body_create_register_user_admin_create_register_user_post } from './models/Body_create_register_user_admin_create_register_user_post';
export type { Body_upload_image_new_upload_image_new_post } from './models/Body_upload_image_new_upload_image_new_post';
export type { Body_upload_image_upload_image_post } from './models/Body_upload_image_upload_image_post';
export type { Body_upload_media_post_upload_post } from './models/Body_upload_media_post_upload_post';
export type { BulkSearchResult } from './models/BulkSearchResult';
export type { Bulletin } from './models/Bulletin';
export type { BulletinCreate } from './models/BulletinCreate';
export type { BulletinList } from './models/BulletinList';
export type { CardEvent } from './models/CardEvent';
export type { CardEventCreate } from './models/CardEventCreate';
export type { CardEventPatch } from './models/CardEventPatch';
export type { CardType } from './models/CardType';
export { CardTypeEnum } from './models/CardTypeEnum';
export type { CardTypeList } from './models/CardTypeList';
export type { ChanceEvent } from './models/ChanceEvent';
export type { ChanceEventCreate } from './models/ChanceEventCreate';
export type { ChanceEventPatch } from './models/ChanceEventPatch';
export type { ChanceType } from './models/ChanceType';
export { ChanceTypeEnum } from './models/ChanceTypeEnum';
export type { ChanceTypeList } from './models/ChanceTypeList';
export type { ChangeEvent } from './models/ChangeEvent';
export type { ChangeEventCreate } from './models/ChangeEventCreate';
export type { ChangeEventPatch } from './models/ChangeEventPatch';
export type { ChangeLogElement } from './models/ChangeLogElement';
export type { ClubListElement } from './models/ClubListElement';
export type { Comment } from './models/Comment';
export type { CommentCreate } from './models/CommentCreate';
export type { CommentList } from './models/CommentList';
export type { CommentPatch } from './models/CommentPatch';
export type { DateList } from './models/DateList';
export type { EventType } from './models/EventType';
export { EventTypeEnum } from './models/EventTypeEnum';
export type { EventTypeList } from './models/EventTypeList';
export type { ExternalVideo } from './models/ExternalVideo';
export type { ExternalVideoCreate } from './models/ExternalVideoCreate';
export type { ExternalVideoCreateRaw } from './models/ExternalVideoCreateRaw';
export type { ExternalVideoList } from './models/ExternalVideoList';
export type { File } from './models/File';
export { FootEnum } from './models/FootEnum';
export type { Format } from './models/Format';
export { FormatTypeEnum } from './models/FormatTypeEnum';
export type { GoalDistribution } from './models/GoalDistribution';
export type { GoalDistributionMatch } from './models/GoalDistributionMatch';
export type { GoalEvent } from './models/GoalEvent';
export type { GoalEventCreate } from './models/GoalEventCreate';
export type { GoalEventPatch } from './models/GoalEventPatch';
export type { GoalType } from './models/GoalType';
export { GoalTypeEnum } from './models/GoalTypeEnum';
export type { GoalTypeList } from './models/GoalTypeList';
export type { Group } from './models/Group';
export { GroupEnum } from './models/GroupEnum';
export type { GroupRequest } from './models/GroupRequest';
export type { HTTPValidationError } from './models/HTTPValidationError';
export { ImageTypeEnum } from './models/ImageTypeEnum';
export { JerseyModeEnum } from './models/JerseyModeEnum';
export type { Language } from './models/Language';
export type { LanguageList } from './models/LanguageList';
export { LanguageLocaleEnum } from './models/LanguageLocaleEnum';
export type { League } from './models/League';
export { LeagueCategoryEnum } from './models/LeagueCategoryEnum';
export type { LeagueCreate } from './models/LeagueCreate';
export type { LeagueList } from './models/LeagueList';
export type { LeagueListElement } from './models/LeagueListElement';
export type { LeagueListMinimum } from './models/LeagueListMinimum';
export type { LeagueMatch } from './models/LeagueMatch';
export type { LeagueMatchList } from './models/LeagueMatchList';
export type { LeaguePatch } from './models/LeaguePatch';
export { LeagueRatingEnum } from './models/LeagueRatingEnum';
export type { Lineup } from './models/Lineup';
export type { LineupCreate } from './models/LineupCreate';
export type { LineupPosition } from './models/LineupPosition';
export type { LineupPositionPlayer } from './models/LineupPositionPlayer';
export type { LineupPositionPlayerCreate } from './models/LineupPositionPlayerCreate';
export type { LineupType } from './models/LineupType';
export type { LineupTypeList } from './models/LineupTypeList';
export type { Location } from './models/Location';
export type { LocationCreate } from './models/LocationCreate';
export type { LocationList } from './models/LocationList';
export type { ManOfTheMatch } from './models/ManOfTheMatch';
export type { ManOfTheMatchListElement } from './models/ManOfTheMatchListElement';
export type { ManOfTheMatchListElementList } from './models/ManOfTheMatchListElementList';
export type { ManOfTheMatchVote } from './models/ManOfTheMatchVote';
export type { Match } from './models/Match';
export type { MatchBetUserVote } from './models/MatchBetUserVote';
export type { MatchBetVoting } from './models/MatchBetVoting';
export type { MatchCreate } from './models/MatchCreate';
export { MatchFixEnum } from './models/MatchFixEnum';
export type { MatchImport } from './models/MatchImport';
export type { MatchImportResult } from './models/MatchImportResult';
export type { MatchImportResultList } from './models/MatchImportResultList';
export type { MatchListElement } from './models/MatchListElement';
export type { MatchListElementList } from './models/MatchListElementList';
export type { MatchListMinimum } from './models/MatchListMinimum';
export { MatchLocationEnum } from './models/MatchLocationEnum';
export type { MatchPatch } from './models/MatchPatch';
export type { Out } from './models/Out';
export type { OutSummary } from './models/OutSummary';
export type { PasswordChange } from './models/PasswordChange';
export type { PasswordReset } from './models/PasswordReset';
export type { Person } from './models/Person';
export type { PersonCreate } from './models/PersonCreate';
export type { Player } from './models/Player';
export type { PlayerCard } from './models/PlayerCard';
export type { PlayerCardEntry } from './models/PlayerCardEntry';
export type { PlayerCreate } from './models/PlayerCreate';
export type { PlayerListElement } from './models/PlayerListElement';
export type { PlayerListElementList } from './models/PlayerListElementList';
export type { PlayerPatch } from './models/PlayerPatch';
export type { PlayerPosition } from './models/PlayerPosition';
export { PlayerPositionEnum } from './models/PlayerPositionEnum';
export type { PlayerPositionList } from './models/PlayerPositionList';
export type { PlayerSearchElement } from './models/PlayerSearchElement';
export type { PlayerSearchElementList } from './models/PlayerSearchElementList';
export type { PlayerStatistic } from './models/PlayerStatistic';
export type { PlayerStatisticDetail } from './models/PlayerStatisticDetail';
export type { PlayerStatisticList } from './models/PlayerStatisticList';
export type { PlayerStatisticListElement } from './models/PlayerStatisticListElement';
export type { Post } from './models/Post';
export type { PostCreate } from './models/PostCreate';
export type { PostPatch } from './models/PostPatch';
export type { Punishment } from './models/Punishment';
export type { PunishmentCreate } from './models/PunishmentCreate';
export type { Scope } from './models/Scope';
export { ScopeEnum } from './models/ScopeEnum';
export type { SearchRequest } from './models/SearchRequest';
export type { SearchResult } from './models/SearchResult';
export { SearchTypeEnum } from './models/SearchTypeEnum';
export type { Sponsor } from './models/Sponsor';
export type { SponsorCreate } from './models/SponsorCreate';
export type { SponsorPatch } from './models/SponsorPatch';
export type { Squad } from './models/Squad';
export type { SquadList } from './models/SquadList';
export type { Standing } from './models/Standing';
export type { StandingList } from './models/StandingList';
export type { Statistic } from './models/Statistic';
export { StatisticKeyEnum } from './models/StatisticKeyEnum';
export type { Task } from './models/Task';
export type { Team } from './models/Team';
export type { TeamCreate } from './models/TeamCreate';
export type { TeamListElement } from './models/TeamListElement';
export type { TeamListElementList } from './models/TeamListElementList';
export type { TeamListMinimum } from './models/TeamListMinimum';
export type { TeamPatch } from './models/TeamPatch';
export type { TeamStatistic } from './models/TeamStatistic';
export type { TeamStatisticDetail } from './models/TeamStatisticDetail';
export type { TeamStatisticList } from './models/TeamStatisticList';
export type { TeamStatisticListElement } from './models/TeamStatisticListElement';
export type { Transfer } from './models/Transfer';
export type { TransferList } from './models/TransferList';
export type { Translation } from './models/Translation';
export type { TranslationCreate } from './models/TranslationCreate';
export type { User } from './models/User';
export type { UserBadge } from './models/UserBadge';
export type { UserBadgeCreateDelete } from './models/UserBadgeCreateDelete';
export type { UserCreate } from './models/UserCreate';
export type { UserEssential } from './models/UserEssential';
export type { UserLogin } from './models/UserLogin';
export type { UserPatch } from './models/UserPatch';
export type { UserRegister } from './models/UserRegister';
export type { ValidationError } from './models/ValidationError';

export { $Ad } from './schemas/$Ad';
export { $AdCreate } from './schemas/$AdCreate';
export { $AdList } from './schemas/$AdList';
export { $AdPatch } from './schemas/$AdPatch';
export { $AdPositionEnum } from './schemas/$AdPositionEnum';
export { $AreaOfInterest } from './schemas/$AreaOfInterest';
export { $AreaOfInterestList } from './schemas/$AreaOfInterestList';
export { $AuthResponse } from './schemas/$AuthResponse';
export { $Badge } from './schemas/$Badge';
export { $BadgeCreate } from './schemas/$BadgeCreate';
export { $BadgeList } from './schemas/$BadgeList';
export { $BadgePatch } from './schemas/$BadgePatch';
export { $BadgeTypeEnum } from './schemas/$BadgeTypeEnum';
export { $BaseBulkSearchResult } from './schemas/$BaseBulkSearchResult';
export { $Blog } from './schemas/$Blog';
export { $BlogCreate } from './schemas/$BlogCreate';
export { $BlogList } from './schemas/$BlogList';
export { $Body_change_team_icon_admin_change_team_icon__team_id__post } from './schemas/$Body_change_team_icon_admin_change_team_icon__team_id__post';
export { $Body_create_register_user_admin_create_register_user_post } from './schemas/$Body_create_register_user_admin_create_register_user_post';
export { $Body_upload_image_new_upload_image_new_post } from './schemas/$Body_upload_image_new_upload_image_new_post';
export { $Body_upload_image_upload_image_post } from './schemas/$Body_upload_image_upload_image_post';
export { $Body_upload_media_post_upload_post } from './schemas/$Body_upload_media_post_upload_post';
export { $BulkSearchResult } from './schemas/$BulkSearchResult';
export { $Bulletin } from './schemas/$Bulletin';
export { $BulletinCreate } from './schemas/$BulletinCreate';
export { $BulletinList } from './schemas/$BulletinList';
export { $CardEvent } from './schemas/$CardEvent';
export { $CardEventCreate } from './schemas/$CardEventCreate';
export { $CardEventPatch } from './schemas/$CardEventPatch';
export { $CardType } from './schemas/$CardType';
export { $CardTypeEnum } from './schemas/$CardTypeEnum';
export { $CardTypeList } from './schemas/$CardTypeList';
export { $ChanceEvent } from './schemas/$ChanceEvent';
export { $ChanceEventCreate } from './schemas/$ChanceEventCreate';
export { $ChanceEventPatch } from './schemas/$ChanceEventPatch';
export { $ChanceType } from './schemas/$ChanceType';
export { $ChanceTypeEnum } from './schemas/$ChanceTypeEnum';
export { $ChanceTypeList } from './schemas/$ChanceTypeList';
export { $ChangeEvent } from './schemas/$ChangeEvent';
export { $ChangeEventCreate } from './schemas/$ChangeEventCreate';
export { $ChangeEventPatch } from './schemas/$ChangeEventPatch';
export { $ChangeLogElement } from './schemas/$ChangeLogElement';
export { $ClubListElement } from './schemas/$ClubListElement';
export { $Comment } from './schemas/$Comment';
export { $CommentCreate } from './schemas/$CommentCreate';
export { $CommentList } from './schemas/$CommentList';
export { $CommentPatch } from './schemas/$CommentPatch';
export { $DateList } from './schemas/$DateList';
export { $EventType } from './schemas/$EventType';
export { $EventTypeEnum } from './schemas/$EventTypeEnum';
export { $EventTypeList } from './schemas/$EventTypeList';
export { $ExternalVideo } from './schemas/$ExternalVideo';
export { $ExternalVideoCreate } from './schemas/$ExternalVideoCreate';
export { $ExternalVideoCreateRaw } from './schemas/$ExternalVideoCreateRaw';
export { $ExternalVideoList } from './schemas/$ExternalVideoList';
export { $File } from './schemas/$File';
export { $FootEnum } from './schemas/$FootEnum';
export { $Format } from './schemas/$Format';
export { $FormatTypeEnum } from './schemas/$FormatTypeEnum';
export { $GoalDistribution } from './schemas/$GoalDistribution';
export { $GoalDistributionMatch } from './schemas/$GoalDistributionMatch';
export { $GoalEvent } from './schemas/$GoalEvent';
export { $GoalEventCreate } from './schemas/$GoalEventCreate';
export { $GoalEventPatch } from './schemas/$GoalEventPatch';
export { $GoalType } from './schemas/$GoalType';
export { $GoalTypeEnum } from './schemas/$GoalTypeEnum';
export { $GoalTypeList } from './schemas/$GoalTypeList';
export { $Group } from './schemas/$Group';
export { $GroupEnum } from './schemas/$GroupEnum';
export { $GroupRequest } from './schemas/$GroupRequest';
export { $HTTPValidationError } from './schemas/$HTTPValidationError';
export { $ImageTypeEnum } from './schemas/$ImageTypeEnum';
export { $JerseyModeEnum } from './schemas/$JerseyModeEnum';
export { $Language } from './schemas/$Language';
export { $LanguageList } from './schemas/$LanguageList';
export { $LanguageLocaleEnum } from './schemas/$LanguageLocaleEnum';
export { $League } from './schemas/$League';
export { $LeagueCategoryEnum } from './schemas/$LeagueCategoryEnum';
export { $LeagueCreate } from './schemas/$LeagueCreate';
export { $LeagueList } from './schemas/$LeagueList';
export { $LeagueListElement } from './schemas/$LeagueListElement';
export { $LeagueListMinimum } from './schemas/$LeagueListMinimum';
export { $LeagueMatch } from './schemas/$LeagueMatch';
export { $LeagueMatchList } from './schemas/$LeagueMatchList';
export { $LeaguePatch } from './schemas/$LeaguePatch';
export { $LeagueRatingEnum } from './schemas/$LeagueRatingEnum';
export { $Lineup } from './schemas/$Lineup';
export { $LineupCreate } from './schemas/$LineupCreate';
export { $LineupPosition } from './schemas/$LineupPosition';
export { $LineupPositionPlayer } from './schemas/$LineupPositionPlayer';
export { $LineupPositionPlayerCreate } from './schemas/$LineupPositionPlayerCreate';
export { $LineupType } from './schemas/$LineupType';
export { $LineupTypeList } from './schemas/$LineupTypeList';
export { $Location } from './schemas/$Location';
export { $LocationCreate } from './schemas/$LocationCreate';
export { $LocationList } from './schemas/$LocationList';
export { $ManOfTheMatch } from './schemas/$ManOfTheMatch';
export { $ManOfTheMatchListElement } from './schemas/$ManOfTheMatchListElement';
export { $ManOfTheMatchListElementList } from './schemas/$ManOfTheMatchListElementList';
export { $ManOfTheMatchVote } from './schemas/$ManOfTheMatchVote';
export { $Match } from './schemas/$Match';
export { $MatchBetUserVote } from './schemas/$MatchBetUserVote';
export { $MatchBetVoting } from './schemas/$MatchBetVoting';
export { $MatchCreate } from './schemas/$MatchCreate';
export { $MatchFixEnum } from './schemas/$MatchFixEnum';
export { $MatchImport } from './schemas/$MatchImport';
export { $MatchImportResult } from './schemas/$MatchImportResult';
export { $MatchImportResultList } from './schemas/$MatchImportResultList';
export { $MatchListElement } from './schemas/$MatchListElement';
export { $MatchListElementList } from './schemas/$MatchListElementList';
export { $MatchListMinimum } from './schemas/$MatchListMinimum';
export { $MatchLocationEnum } from './schemas/$MatchLocationEnum';
export { $MatchPatch } from './schemas/$MatchPatch';
export { $Out } from './schemas/$Out';
export { $OutSummary } from './schemas/$OutSummary';
export { $PasswordChange } from './schemas/$PasswordChange';
export { $PasswordReset } from './schemas/$PasswordReset';
export { $Person } from './schemas/$Person';
export { $PersonCreate } from './schemas/$PersonCreate';
export { $Player } from './schemas/$Player';
export { $PlayerCard } from './schemas/$PlayerCard';
export { $PlayerCardEntry } from './schemas/$PlayerCardEntry';
export { $PlayerCreate } from './schemas/$PlayerCreate';
export { $PlayerListElement } from './schemas/$PlayerListElement';
export { $PlayerListElementList } from './schemas/$PlayerListElementList';
export { $PlayerPatch } from './schemas/$PlayerPatch';
export { $PlayerPosition } from './schemas/$PlayerPosition';
export { $PlayerPositionEnum } from './schemas/$PlayerPositionEnum';
export { $PlayerPositionList } from './schemas/$PlayerPositionList';
export { $PlayerSearchElement } from './schemas/$PlayerSearchElement';
export { $PlayerSearchElementList } from './schemas/$PlayerSearchElementList';
export { $PlayerStatistic } from './schemas/$PlayerStatistic';
export { $PlayerStatisticDetail } from './schemas/$PlayerStatisticDetail';
export { $PlayerStatisticList } from './schemas/$PlayerStatisticList';
export { $PlayerStatisticListElement } from './schemas/$PlayerStatisticListElement';
export { $Post } from './schemas/$Post';
export { $PostCreate } from './schemas/$PostCreate';
export { $PostPatch } from './schemas/$PostPatch';
export { $Punishment } from './schemas/$Punishment';
export { $PunishmentCreate } from './schemas/$PunishmentCreate';
export { $Scope } from './schemas/$Scope';
export { $ScopeEnum } from './schemas/$ScopeEnum';
export { $SearchRequest } from './schemas/$SearchRequest';
export { $SearchResult } from './schemas/$SearchResult';
export { $SearchTypeEnum } from './schemas/$SearchTypeEnum';
export { $Sponsor } from './schemas/$Sponsor';
export { $SponsorCreate } from './schemas/$SponsorCreate';
export { $SponsorPatch } from './schemas/$SponsorPatch';
export { $Squad } from './schemas/$Squad';
export { $SquadList } from './schemas/$SquadList';
export { $Standing } from './schemas/$Standing';
export { $StandingList } from './schemas/$StandingList';
export { $Statistic } from './schemas/$Statistic';
export { $StatisticKeyEnum } from './schemas/$StatisticKeyEnum';
export { $Task } from './schemas/$Task';
export { $Team } from './schemas/$Team';
export { $TeamCreate } from './schemas/$TeamCreate';
export { $TeamListElement } from './schemas/$TeamListElement';
export { $TeamListElementList } from './schemas/$TeamListElementList';
export { $TeamListMinimum } from './schemas/$TeamListMinimum';
export { $TeamPatch } from './schemas/$TeamPatch';
export { $TeamStatistic } from './schemas/$TeamStatistic';
export { $TeamStatisticDetail } from './schemas/$TeamStatisticDetail';
export { $TeamStatisticList } from './schemas/$TeamStatisticList';
export { $TeamStatisticListElement } from './schemas/$TeamStatisticListElement';
export { $Transfer } from './schemas/$Transfer';
export { $TransferList } from './schemas/$TransferList';
export { $Translation } from './schemas/$Translation';
export { $TranslationCreate } from './schemas/$TranslationCreate';
export { $User } from './schemas/$User';
export { $UserBadge } from './schemas/$UserBadge';
export { $UserBadgeCreateDelete } from './schemas/$UserBadgeCreateDelete';
export { $UserCreate } from './schemas/$UserCreate';
export { $UserEssential } from './schemas/$UserEssential';
export { $UserLogin } from './schemas/$UserLogin';
export { $UserPatch } from './schemas/$UserPatch';
export { $UserRegister } from './schemas/$UserRegister';
export { $ValidationError } from './schemas/$ValidationError';

export { AdService } from './services/AdService';
export { AdministrationService } from './services/AdministrationService';
export { AppService } from './services/AppService';
export { AreaOfInterestService } from './services/AreaOfInterestService';
export { AuthenticationService } from './services/AuthenticationService';
export { BadgeService } from './services/BadgeService';
export { BlogService } from './services/BlogService';
export { BulletinService } from './services/BulletinService';
export { CommentService } from './services/CommentService';
export { DefaultService } from './services/DefaultService';
export { EventService } from './services/EventService';
export { ExternalVideoService } from './services/ExternalVideoService';
export { FeedService } from './services/FeedService';
export { FileService } from './services/FileService';
export { GoalDistributionService } from './services/GoalDistributionService';
export { ImportService } from './services/ImportService';
export { LanguageService } from './services/LanguageService';
export { LeagueService } from './services/LeagueService';
export { LineupService } from './services/LineupService';
export { LocationService } from './services/LocationService';
export { ManOfTheMatchService } from './services/ManOfTheMatchService';
export { MatchService } from './services/MatchService';
export { MatchBetService } from './services/MatchBetService';
export { MatchDayService } from './services/MatchDayService';
export { MediaService } from './services/MediaService';
export { MonitorwerbungService } from './services/MonitorwerbungService';
export { OutService } from './services/OutService';
export { PlayerService } from './services/PlayerService';
export { PostService } from './services/PostService';
export { PunishmentService } from './services/PunishmentService';
export { SearchService } from './services/SearchService';
export { SponsorService } from './services/SponsorService';
export { SquadService } from './services/SquadService';
export { StandingService } from './services/StandingService';
export { StatisticsService } from './services/StatisticsService';
export { TaskService } from './services/TaskService';
export { TeamService } from './services/TeamService';
export { TransferService } from './services/TransferService';
export { UserService } from './services/UserService';
